Add a trigger to activate the beid abstraction to the firefox and firefox-esr apparmor on firefox installation.

diff --git a/debian/beid-mozilla-extension.postinst b/debian/beid-mozilla-extension.postinst
--- a/debian/beid-mozilla-extension.postinst
+++ b/debian/beid-mozilla-extension.postinst
@@ -20,3 +20,18 @@ EOF
 		exit 1;
 	fi
 fi
+
+if [ -f /etc/apparmor.d/usr.bin.firefox-esr ]; then
+	if [ -f /etc/apparmor.d/local/usr.bin.firefox-esr ]; then
+		if ! grep -q abstractions/beid /etc/apparmor.d/local/usr.bin.firefox-esr; then
+			cat >> /etc/apparmor.d/local/usr.bin.firefox-esr <<EOF
+# For BeID
+  #include <abstractions/beid>
+EOF
+			apparmor_parser -r -W -T /etc/apparmor.d/usr.bin.firefox-esr || true
+		fi
+	else
+		echo "IEK: usr.bin.firefox-esr apparmor profile exists, but local/usr.bin.firefox-esr does not. Can't fix up firefox-esr profile!" >&2
+		exit 1;
+	fi
+fi
